### ISSUE TITLE
Функция должна быть с префиксом как и остальных функций в плагине

### ISSUE THREAD

**Issue by MjHead** [RagnarLodbrok94/rag-liked-post#1]
https://github.com/RagnarLodbrok94/rag-liked-post/blob/de76c8246e8c3c893e59e9a651d9668080c99778/rag-liked-post.php#L66

https://github.com/RagnarLodbrok94/rag-liked-post/blob/de76c8246e8c3c893e59e9a651d9668080c99778/rag-liked-post.php#L121-L125

**Comment by RagnarLodbrok94** [comment]
Поправил.
Саня обращал на это мое внимание. Мой провтык и копипаст еще, забыл изменить сразу
Изменил немного префикс rag_lp_
