### ISSUE TITLE
Если объявил эту константу логично было бы ее использовать дальше, где нужна переменная __FILE__

### ISSUE THREAD

**Issue by MjHead** [RagnarLodbrok94/rag-liked-post#2]
https://github.com/RagnarLodbrok94/rag-liked-post/blob/de76c8246e8c3c893e59e9a651d9668080c99778/rag-liked-post.php#L13

**Comment by RagnarLodbrok94** [comment]
Поправил. Так получилось, что я ее почти в самом конце завел и совсем завтыкал позаменять.
